"""
Music Royalty Statement Pipeline — Step 3: score the checks
Compares what etl_pipeline.py flagged (output/validation_exceptions.csv)
against the ground-truth manifest of injected issues, file by file, and
reconciles loaded dollars back to the true earnings implied by the source
streams. Writes output/check_evaluation.md.
"""
import os
import sqlite3

import pandas as pd

BASE = os.path.join(os.path.dirname(__file__), "..")
REF = os.path.join(BASE, "data", "reference")
OUT = os.path.join(BASE, "output")


def md(df, fmt="{:,.2f}", index=False):
    """Minimal markdown table (avoids an extra tabulate dependency)."""
    d = df.reset_index() if index else df
    cells = [[fmt.format(v) if isinstance(v, float) else str(v) for v in row] for row in d.itertuples(index=False)]
    head = "| " + " | ".join(map(str, d.columns)) + " |\n|" + "---|" * len(d.columns) + "\n"
    return head + "\n".join("| " + " | ".join(r) + " |" for r in cells)


man = pd.read_csv(os.path.join(REF, "injection_manifest.csv"))
exc = pd.read_csv(os.path.join(OUT, "validation_exceptions.csv"))

# Normalize "file" keys: missing statements are logged by the ETL as "<dist>_<period>"
man["key"] = man.file.str.replace(".csv", "", regex=False).str.replace(".xlsx", "", regex=False)
exc["key"] = exc.statement_file.str.replace(".csv", "", regex=False).str.replace(".xlsx", "", regex=False)

rows = []
for issue, g in man.groupby("issue"):
    flagged = exc[exc.check_name == issue]
    inj_files = set(g.key)
    hit_files = set(flagged.key)
    tp = len(inj_files & hit_files)
    row = dict(issue=issue, files_injected=len(inj_files), files_flagged=len(hit_files),
               files_caught=tp, file_recall=tp / len(inj_files),
               file_precision=(tp / len(hit_files)) if hit_files else float("nan"),
               rows_injected=int(g.rows_affected.sum()), rows_flagged=int(flagged.rows_affected.sum()))
    rows.append(row)
res = pd.DataFrame(rows)

# Checks that fire on things nobody injected = findings in the REAL source data
extra = exc[~exc.check_name.isin(man.issue)].groupby("check_name").agg(
    exceptions=("key", "size"), rows=("rows_affected", "sum")).reset_index()

# ---- Dollar reconciliation against true earnings implied by the real streams
con = sqlite3.connect(os.path.join(OUT, "royalty_dw.db"))
loaded = pd.read_sql("SELECT distributor, SUM(net_usd) usd FROM fact_royalty_line "
                     "WHERE is_adjustment = 0 GROUP BY distributor", con).set_index("distributor").usd
adj = pd.read_sql("SELECT SUM(net_usd) FROM fact_royalty_line WHERE is_adjustment = 1", con).iat[0, 0]
q = pd.read_sql("SELECT quarantine_reason, COUNT(*) n FROM quarantine_line GROUP BY 1", con)
con.close()

raw = pd.read_csv(os.path.join(BASE, "data", "raw", "spotify-charts.csv"))
raw["track_id"] = raw.URL.str.rsplit("/", n=1).str[-1]
raw["month"] = raw.Week.str[:7]
terr = pd.read_csv(os.path.join(REF, "territories.csv"), keep_default_na=False)
cat = pd.read_csv(os.path.join(REF, "master_catalog.csv"))
t = raw.merge(terr, left_on="Country", right_on="territory").merge(cat[["track_id", "distributor"]], on="track_id")
t["usd"] = t.Streams * t.rate_usd
t.loc[t.distributor == "C", "usd"] *= 0.91                   # C pays net of its 9% fee
truth = t.groupby("distributor").usd.sum()
truth_c_ex_june = t[(t.distributor == "C") & (t.month != "2019-06")].usd.sum()

recon = pd.DataFrame({"true_usd": truth, "loaded_usd": loaded})
recon.loc["C", "true_usd_excl_missing_june"] = truth_c_ex_june
recon["gap_usd"] = recon.loaded_usd - recon.true_usd_excl_missing_june.fillna(recon.true_usd)
recon["gap_pct"] = recon.gap_usd / recon.true_usd_excl_missing_june.fillna(recon.true_usd)

with open(os.path.join(OUT, "check_evaluation.md"), "w", encoding="utf-8") as f:
    f.write("# Validation check evaluation\n\n")
    f.write("Generated by `scripts/evaluate_checks.py`. Compares every exception the ETL raised against the ground-truth "
            "manifest of issues injected into the synthetic statements (`data/reference/injection_manifest.csv`). "
            "The ETL never reads that manifest.\n\n")
    f.write("## Injected issues: caught vs. missed\n\n")
    f.write(md(res) + "\n\n")
    f.write("`rows_injected` is 0 for file-level issues (footer mismatch). For `missing_statement` the ETL cannot count "
            "lines that never arrived, so it logs 0 rows.\n\n")
    f.write("## Findings not injected (real source-data behaviour)\n\n")
    f.write(md(extra) + "\n\n")
    f.write("## Dollar reconciliation (net USD, excluding adjustment lines)\n\n")
    f.write(md(recon, index=True) + "\n\n")
    f.write(f"Adjustment lines (reversals + chargebacks) loaded separately: USD {adj:,.2f}.  \n")
    f.write(f"Quarantined lines: {q.set_index('quarantine_reason').n.to_dict()}.\n")

print(res.to_string(index=False))
print(extra.to_string(index=False))
print(recon.to_string())
print("adjustments", adj)
